name: pubgm-hud

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pubgm-hud-api
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - 3011:3011
    volumes:
      - ../.env:/pubgm-hud/.env
      - pubgm-hud-static:/pubgm-hud/static
      - pubgm-hud-db:/pubgm-hud/database_storage

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: pubgm-hud-frontend
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    volumes:
      - ../.env:/pubgm-hud/.env
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN:-localhost}

volumes:
  pubgm-hud-db:
  pubgm-hud-static:
